### ISSUE TITLE
建议：如果内容是空的则不要创建文件

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [ArtformGames/ResidenceList#27]
<img width="261" alt="image" src="https://github.com/ArtformGames/ResidenceList/assets/45261195/5dcfaf74-e248-4c6c-bae2-a71f5ee21001">

现在貌似会给每个人都创建一个文件，但是里面只有一个空的pinned，在规模较大的服务器上会浪费许多空间。

**Comment by CarmJos** [comment]
您好，您的建议非常棒！

我已在 [此提交](https://github.com/ArtformGames/ResidenceList/commit/7fb00375deeb47f8dc0b318b15c7aed0c94a09d5#diff-f35103f068e191d5d8933637b2d4217d8f90a78728ccab1bada951a8d1c83590L9) 中实现，请 [点击这里](https://github.com/ArtformGames/ResidenceList/actions/runs/7768070053) 下载 `assets.zip` ，并安装其中的插件帮助测试，非常感谢！

**Comment by CarmJos** [comment]
需要注意的是，该版本不会删除已有的空数据，而是在玩家后续离开时不再保存或清理空的数据文件。

**Comment by Aira-Sakuranomiya** [comment]
感谢实现！
我已下载并测试，但插件加载出现错误，日志如下：

```
[03:30:16 INFO]: [ResidenceList] Enabling ResidenceList v1.2.0
[03:30:16 INFO]: [ResidenceList]    ___          _    __                 __   _     __
[03:30:16 INFO]: [ResidenceList]   / _ \___ ___ (_)__/ /__ ___  _______ / /  (_)__ / /_
[03:30:16 INFO]: [ResidenceList]  / , _/ -_|_-</ / _  / -_) _ \/ __/ -_) /__/ (_-</ __/
[03:30:16 INFO]: [ResidenceList] /_/|_|\__/___/_/\_,_/\__/_//_/\__/\__/____/_/___/\__/
[03:30:16 INFO]: [ResidenceList] # ResidenceList v1.2.0
[03:30:16 INFO]: [ResidenceList] > View at https://github.com/ArtformGames/ResidenceList
[03:30:16 INFO]: [ResidenceList] ResidenceList 1.2.0 enabling...
[03:30:16 INFO]: [ResidenceList] Loading storage data...
[03:30:16 ERROR]: Error occurred while enabling ResidenceList v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.artformgames.plugin.residencelist.api.storage.DataStorage.initialize()" because "this.storage" is null
        at com.artformgames.plugin.residencelist.Main.initialize(Main.java:55) ~[ResidenceList-1.2.0.jar:?]
        at com.artformgames.plugin.residencelist.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71) ~[ResidenceList-1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[03:30:16 INFO]: [ResidenceList] Disabling ResidenceList v1.2.0
```

**Comment by CarmJos** [comment]
您好，很抱歉耽搁了您的时间，请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7772307276) 后再试一次吧！

**Comment by CarmJos** [comment]
请问使用情况如何？有解决您的顾虑吗？

**Comment by Sraconni** [comment]
> 您好，很抱歉耽搁了您的时间，请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7772561867) 后再试一次吧！

![image](https://github.com/ArtformGames/ResidenceList/assets/108390647/eb82eb1c-3d5b-4804-b6e1-3220ffe6c943)
该构件版本中，用户的数据加载似乎还有些问题。

**Comment by CarmJos** [comment]
> > 您好，很抱歉耽搁了您的时间，请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7772561867) 后再试一次吧！
> 
> ![image](https://private-user-images.githubusercontent.com/108390647/302124647-241ba192-2e34-4e0c-b739-1a0ef3ab76a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzA5OTUsIm5iZiI6MTcwNzA3MDY5NSwicGF0aCI6Ii8xMDgzOTA2NDcvMzAyMTI0NjQ3LTI0MWJhMTkyLTJlMzQtNGUwYy1iNzM5LTFhMGVmM2FiNzZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxODE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDVmMzFlMGJmMjU2OGUyYTdlYWQ4MmQxY2ExYjhmMjI5NWZhMmUxOTE2ZjM2NTMzNDQ3ZmUzOWFkZjBkOTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vLtCF7T_Nn4cCzt5bRYdyk6ovYO1SFNlR8DevpgfeSg) 该构件版本中，用户的数据加载似乎还有些问题。

在 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7775922263) 中应当修复了。

**Comment by Sraconni** [comment]
> > > 您好，很抱歉耽搁了您的时间，请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7772561867) 后再试一次吧！
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/108390647/302124647-241ba192-2e34-4e0c-b739-1a0ef3ab76a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzA5OTUsIm5iZiI6MTcwNzA3MDY5NSwicGF0aCI6Ii8xMDgzOTA2NDcvMzAyMTI0NjQ3LTI0MWJhMTkyLTJlMzQtNGUwYy1iNzM5LTFhMGVmM2FiNzZhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQxODE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMDVmMzFlMGJmMjU2OGUyYTdlYWQ4MmQxY2ExYjhmMjI5NWZhMmUxOTE2ZjM2NTMzNDQ3ZmUzOWFkZjBkOTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vLtCF7T_Nn4cCzt5bRYdyk6ovYO1SFNlR8DevpgfeSg) 该构件版本中，用户的数据加载似乎还有些问题。
> 
> 在 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/7775922263) 中应当修复了。

一切正常，更新后的用户数据的处理方式看起来很棒。现在的用户数据只会在有内容时存储在本地，当用户数据为空的时候则会自动删除。
