### ISSUE TITLE
[suggestion] folia support

### ISSUE THREAD

**Issue by cgw2023** [ArtformGames/ResidenceList#40]
### **Description**

please add folia support to this plugin
folia is another server jar 
https://github.com/PaperMC/Folia/issues

### **Source**

folia server cannot run this plugin

### **Examples** _(Optional)_

```
[13:49:06 ERROR]: Error occurred while enabling ResidenceList v1.2.0 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:259) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:246) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:191) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:160) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at com.artformgames.plugin.residencelist.lib.easyplugin.utils.SchedulerUtils.runAsync(SchedulerUtils.java:42) ~[ResidenceList-1.2.0.jar:?]
        at com.artformgames.plugin.residencelist.Main.initialize(Main.java:83) ~[ResidenceList-1.2.0.jar:?]
        at com.artformgames.plugin.residencelist.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71) ~[ResidenceList-1.2.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:49:06 INFO]: [ResidenceList] Disabling ResidenceList v1.2.0
```

### **AddItional details**
folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf-25ee657

**Comment by CarmJos** [comment]
With highly combined with BukkitScheduler (Async tasks), we may have some difficult to support Folia, that means this support could not be implement in a short days.

But, we are working hard to support more platforms now, so please continue watching this project!

**Comment by CarmJos** [comment]
Try to disable "check-update" in configuration?

**Comment by cgw2023** [comment]
> Try to disable "check-update" in configuration?
yes that can run but some of the function is not working. such as set residence name
![image](https://github.com/user-attachments/assets/1b4d4ea7-d5f4-42bc-a671-62b9ae8020ec)

![image](https://github.com/user-attachments/assets/f7f710eb-29ca-4c65-9820-51041273d850)

**Comment by CarmJos** [comment]
Does foila removed "AsyncPlayerChatEvent"? Okay...

IDK if there are any documentations that shows the differences or precautions when using folia to develop plugins, so I may cannot to solve all of them. 

If there are any pages, please post it to me, thanks!

**Comment by cgw2023** [comment]
I saw this, not sure whether this can help or not https://github.com/PaperMC/Folia/issues/290
