### ISSUE TITLE
Compatibility error in 1.21

### ISSUE THREAD

**Issue by MingGRE** [ArtformGames/ResidenceList#45]
## **Description**

The plugin can be loaded, but it cannot display the content correctly.

## **Logs**

```
[01:28:44 WARN]: java.lang.IllegalArgumentException: **NETHER_PORTAL** isn't an item
[01:28:44 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.xseries.XItemStack.deserialize(XItemStack.java:420)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.lambda$new$0(ConfiguredItem.java:29)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.configuration.core.value.type.ConfiguredSection.get(ConfiguredSection.java:68)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.getOptional(ConfiguredItem.java:41)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:46)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.lambda$prepare$2(ConfiguredItem.java:57)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.PreparedItem.get(PreparedItem.java:25)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:74)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:61)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI.<init>(ResidenceListUI.java:48)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI.open(ResidenceListUI.java:34)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI$3.onClick(ResidenceListUI.java:110)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.easyplugin.gui.GUIListener.onInventoryClickEvent(GUIListener.java:48)
[01:28:44 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor397.execute(Unknown Source)
[01:28:44 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:28:44 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[01:28:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:28:44 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:28:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[01:28:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:28:44 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122)
[01:28:44 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[01:28:44 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[01:28:44 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[01:28:44 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:28:44 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[01:28:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[01:28:44 WARN]: java.lang.IllegalArgumentException: NETHER_PORTAL isn't an item
[01:28:44 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104)
[01:28:44 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.xseries.XItemStack.deserialize(XItemStack.java:420)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.lambda$new$0(ConfiguredItem.java:29)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.configuration.core.value.type.ConfiguredSection.get(ConfiguredSection.java:68)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.getOptional(ConfiguredItem.java:41)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:46)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.lambda$prepare$2(ConfiguredItem.java:57)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.PreparedItem.get(PreparedItem.java:25)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:74)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ConfiguredItem.get(ConfiguredItem.java:61)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI.<init>(ResidenceListUI.java:49)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI.open(ResidenceListUI.java:34)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.ui.ResidenceListUI$3.onClick(ResidenceListUI.java:110)
[01:28:44 WARN]:        at ResidenceList-1.2.0.jar//com.artformgames.plugin.residencelist.lib.easyplugin.gui.GUIListener.onInventoryClickEvent(GUIListener.java:48)
[01:28:44 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor397.execute(Unknown Source)
[01:28:44 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:28:44 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[01:28:44 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:28:44 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:28:44 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[01:28:44 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[01:28:44 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122)
[01:28:44 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[01:28:44 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[01:28:44 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[01:28:44 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[01:28:44 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[01:28:44 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1478)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1323)
[01:28:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[01:28:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

## **Environment**

- System: `Windows 10`
- Java version: `JDK23`

**Comment by CarmJos** [comment]
Please download [this artifact](https://github.com/ArtformGames/ResidenceList/actions/runs/10019797861) to test whether this problem has been fixed.

**Comment by MingGRE** [comment]
> Please download [this artifact](https://github.com/ArtformGames/ResidenceList/actions/runs/10019797861) to test whether this problem has been fixed.

This build is ok now in 1.12.
