### ISSUE TITLE
When the territory owner is server, using /reslist info will generate an error

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#50]
```
[20:28:45 INFO]: RiceChen_ issued server command: /reslist info end
[20:28:45 WARN]: java.lang.NullPointerException: Profile name must not be null
[20:28:45 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:259)
[20:28:45 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[20:28:45 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ItemModifier.lambda$setSkullOwner$6(ItemModifier.java:201)
[20:28:45 WARN]:        at java.base/java.util.function.BiConsumer.lambda$andThen$0(BiConsumer.java:72)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.ItemModifier.applyTo(ItemModifier.java:74)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.lib.mineconfiguration.bukkit.value.item.PreparedItem.get(PreparedItem.java:28)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.ui.ResidenceInfoUI.initItems(ResidenceInfoUI.java:106)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.ui.ResidenceInfoUI.<init>(ResidenceInfoUI.java:57)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.ui.ResidenceInfoUI.open(ResidenceInfoUI.java:36)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.command.user.InfoCommand.execute(InfoCommand.java:40)
[20:28:45 WARN]:        at ResidenceList-1.2.1.jar//com.artformgames.plugin.residencelist.lib.easyplugin.command.CommandHandler.onCommand(CommandHandler.java:107)
[20:28:45 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:28:45 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[20:28:45 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1005)
[20:28:45 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[20:28:45 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[20:28:45 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:338)
[20:28:45 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322)
[20:28:45 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2279)
[20:28:45 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2239)
[20:28:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[20:28:45 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:28:45 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:28:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:28:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1351)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[20:28:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1328)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1321)
[20:28:45 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1299)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1187)
[20:28:45 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[20:28:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by CarmJos** [comment]
Will be fixed in next version. Thank you for your issues.

**Comment by CarmJos** [comment]
Please download this [artifact](https://github.com/ArtformGames/ResidenceList/actions/runs/10863070098/artifacts/1933215115) to help me to test it.

**Comment by RICE0707** [comment]
> Will be fixed in next version. Thank you for your issues.

> 請下載這個[神器](https://github.com/ArtformGames/ResidenceList/actions/runs/10863070098/artifacts/1933215115)來幫我測試它。

ERROR
```
[10:45:10] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'residencelist-plugin-1.2.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/artformgames/plugin/residencelist/ResidenceListPlugin
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/artformgames/plugin/residencelist/ResidenceListPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.2.jar:git-Purpur-2095]
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.artformgames.plugin.residencelist.ResidenceListPlugin
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.2.jar:git-Purpur-2095]
	... 9 more
```

**Comment by CarmJos** [comment]
您好，请您下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/10904312065/artifacts/1942821103) 以协助我们进行测试，万分感谢！

**Comment by RICE0707** [comment]
> 您好，请您下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/10904312065/artifacts/1942821103) 以协助我们进行测试，万分感谢！

 經測試後已修正
![image](https://github.com/user-attachments/assets/630b539e-8e5c-48b8-acfc-674461638f39)

**Comment by CarmJos** [comment]
感谢您的帮助，我将在稍后发布新版本~
