### ISSUE TITLE
List data won't be removed when residence is removed, When the server starts, error occurred "residence not found".

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#62]
```
[00:50:19] [Server thread/INFO]: [ResidenceList] [ERROR] Error occurred when loading residence data #/home/container/plugins/ResidenceList/residences/temp01.yaml !
[00:50:19] [Server thread/WARN]: java.lang.Exception: Residence not found: temp01
[00:50:19] [Server thread/WARN]: 	at ResidenceList-1.3.1.jar//com.artformgames.plugin.residencelist.storage.yaml.YAMLStorage.loadResidence(YAMLStorage.java:162)
[00:50:19] [Server thread/WARN]: 	at ResidenceList-1.3.1.jar//com.artformgames.plugin.residencelist.storage.yaml.YAMLStorage.loadAllResidences(YAMLStorage.java:146)
[00:50:19] [Server thread/WARN]: 	at ResidenceList-1.3.1.jar//com.artformgames.plugin.residencelist.storage.yaml.YAMLStorage.initialize(YAMLStorage.java:43)
[00:50:19] [Server thread/WARN]: 	at ResidenceList-1.3.1.jar//com.artformgames.plugin.residencelist.Main.initialize(Main.java:57)
[00:50:19] [Server thread/WARN]: 	at ResidenceList-1.3.1.jar//com.artformgames.plugin.residencelist.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71)
[00:50:19] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[00:50:19] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[00:50:19] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[00:50:19] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[00:50:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:660)
[00:50:19] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:571)
[00:50:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:632)
[00:50:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:429)
[00:50:19] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[00:50:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1102)
[00:50:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[00:50:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by CarmJos** [comment]
在玩家自行移除领地时，本插件也会自动移除相关数据。

若在关服或插件未启用时移除，则数据仍会保留，插件会提示领地的缺失，但不影响其正常加载。

**Comment by RICE0707** [comment]
> 在玩家自行移除领地时，本插件也会自动移除相关数据。
> 
> 若在关服或插件未启用时移除，则数据仍会保留，插件会提示领地的缺失，但不影响其正常加载。

但是這個 error 在啟動時很刷，希望這些數據都可以移除，因為領地不存在了

**Comment by CarmJos** [comment]
请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/11307980321/artifacts/2049002926) 。 在本构建中，额外新增了 `settings.auto-remove` 选项，将自动删除丢失领地的数据。

另外，若您认可本项目，欢迎您 Star + Watch 以获取项目的最新消息，非常感谢您的支持~

**Comment by RICE0707** [comment]
> 请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/11307980321/artifacts/2049002926) 。 在本构建中，额外新增了 `settings.auto-remove` 选项，将自动删除丢失领地的数据。
> 
> 另外，若您认可本项目，欢迎您 Star + Watch 以获取项目的最新消息，非常感谢您的支持~

了解，我會在伺服器重啟後再次觀察數據是否移除，感謝開發

**Comment by CarmJos** [comment]
> > 请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/11307980321/artifacts/2049002926) 。 在本构建中，额外新增了 `settings.auto-remove` 选项，将自动删除丢失领地的数据。
> > 另外，若您认可本项目，欢迎您 Star + Watch 以获取项目的最新消息，非常感谢您的支持~
> 
> 了解，我會在伺服器重啟後再次觀察數據是否移除，感謝開發

若问题已解决，请关闭本议题。关闭后，我将发布新版本。

感谢您的star，您的支持是我们最大的动力。
